parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 6
  project: tsconfig.json

env:
  browser: true

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - prettier

plugins:
  - prettier

rules:
  prettier/prettier: error
  react/react-in-jsx-scope: off
  react/prop-types: ['error', { 'ignore': ['navigation'] }]
  no-bitwise: ['error', { 'allow': ['~'] }]
  no-alert: 0
  no-console: 0
  object-curly-newline: 0
  react/jsx-props-no-spreading: 0
  react/require-default-props: 0
  react/no-children-prop: 0
  no-nested-ternary: 0
  '@typescript-eslint/object-curly-spacing': 0
  '@typescript-eslint/no-use-before-define': 0
  '@typescript-eslint/no-non-null-assertion': off